synapse_ids:
  cibersort_results: "syn14718729"
  mcpcounter_results: "syn14718731"
  ground_truth: "syn14718638"
  ground_truth_sd: "syn14718640"
  log_tpm_expression: "syn14718622"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn14718635"
cibersort_common_groups:
 - "T_cells"
 - "CD4_T_cells"
 - "CD8_T_cells"
gt_cs_groups:
cs_gt_groups: 
  - {new_col: "T_cells", old_cols: ["T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated",
  "T_cells_CD8", "T_cells_gamma_delta"]}
  - {new_col: "CD4_T_cells", old_cols: ["T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated"]}
  - {new_col: "CD8_T_cells", old_cols: "T_cells_CD8"}
mcpcounter_common_groups:
 - "T_cells"
gt_mcp_groups:
mcp_gt_groups: 
pca_plot_aes:
  color: "gender"
  shape: "race"
  size: "age"
  
