synapse_ids:
  cibersort_results: "syn11969430"
  ground_truth: "syn12650217"
  mcpcounter_results: "syn11969431"
  log_tpm_expression: "syn12979151"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn12971001"
cibersort_common_groups:
 - "B_cells"
 - "Monocytes"
 - "T_cells"
 - "NK_cells"
 - "Other_cells"
gt_cs_groups:
cs_gt_groups: 
  - {new_col: "B_cells", old_cols: ["B_cells_naive", "B_cells_memory"]}
  - {new_col: "T_cells", old_cols: ["T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated",
  "T_cells_CD8", "T_cells_follicular_helper", "T_cells_gamma_delta"]}
  - {new_col: "NK_cells", old_cols: ["NK_cells_resting",  "NK_cells_activated"]} 
  - {new_col: "Other_cells", old_cols: ["Plasma_cells", "Macrophages_M0",
  "Macrophages_M1", "Macrophages_M2", "Dendritic_cells_resting", "Dendritic_cells_activated",
  "Mast_cells_resting", "Mast_cells_activated", "Eosinophils", "Neutrophils"]}
 
mcpcounter_common_groups:
 - "B_cells"
 - "NK_cells"
 - "T_cells"
gt_mcp_groups:
mcp_gt_groups: 
  - {new_col: "Monocytes", old_cols: "Monocytic_lineage"}
  - {new_col: "B_cells", old_cols: "B_lineage"}
pca_plot_aes:
  color: "patient"
  shape: "cell_type"
  size: 
  
  
