synapse_ids:
  cibersort_results: "syn18266331"
  mcpcounter_results: "syn18266342"
  ground_truth: "syn17098226"
  log_expression: "syn18257907"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn17098225"
dont_normalize_ground_truth_to_one: true
sum_cibersort_results_to_one: true

cibersort_common_groups:
 - "Neutrophils"
 - "Lymphocytes"
 - "Monocytes"
 - "Eosinophils"
 
gt_cs_groups:
 - {new_col: "Neutrophils", old_cols: ["Neutrophils___"]}
 - {new_col: "Lymphocytes", old_cols: ["Lymphocytes___"]}
 - {new_col: "Monocytes", old_cols: ["Monocytes___"]}
 - {new_col: "Eosinophils", old_cols: ["Eosinophils___"]}
  
cs_gt_groups:
 - {new_col: "Neutrophils", old_cols: ["Neutrophils"]}
 - {new_col: "Lymphocytes", old_cols: ["B_cells_naive", "B_cells_memory",
  "T_cells_CD4_naive",
  "T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated",
  "T_cells_regulatory__Tregs_",
  "T_cells_CD8", "T_cells_gamma_delta",
  "NK_cells_resting",  "NK_cells_activated"]}
 - {new_col: "Monocytes", old_cols: ["Monocytes"]}
 - {new_col: "Eosinophils", old_cols: ["Eosinophils"]}

mcpcounter_common_groups:
 - "Neutrophils"
 - "Lymphocytes"
 - "Monocytes"
 
gt_mcp_groups:
 - {new_col: "Neutrophils", old_cols: ["Neutrophils___"]}
 - {new_col: "Lymphocytes", old_cols: ["Lymphocytes___"]}
 - {new_col: "Monocytes", old_cols: ["Monocytes___"]}
 
mcp_gt_groups:
 - {new_col: "Neutrophils", old_cols: ["Neutrophils"]}
 - {new_col: "Lymphocytes", old_cols: ["Cytotoxic_lymphocytes"]}
 - {new_col: "Monocytes", old_cols: ["Monocytic_lineage"]}
