synapse_ids:
  cibersort_results: "syn17895742"
  mcpcounter_results: "syn17895747"
  ground_truth: "syn17091819"
  log_expression: "syn17088619"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn17091819"
sum_cibersort_results_to_one: true
cibersort_common_groups:
 - "Eosinophils"
 - "Lymphocytes"
 - "Monocytes"
 - "Neutrophils"
gt_cs_groups:
 - {new_col: "Eosinophils", old_cols: ["eosinophil"]}
 - {new_col: "Lymphocytes", old_cols: ["lymphocyte"]}  
 - {new_col: "Monocytes", old_cols: ["monocyte"]}
 - {new_col: "Neutrophils", old_cols: ["neutrophil"]}
cs_gt_groups:
 - {new_col: "Lymphocytes", old_cols: ["B_cells_naive", "B_cells_memory",
                                       "T_cells_CD4_naive",
                                       "T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated",
                                       "T_cells_follicular_helper", "T_cells_regulatory__Tregs_",
                                       "T_cells_gamma_delta", "T_cells_CD8", 
                                       "NK_cells_resting",  "NK_cells_activated", "Plasma_cells"]}

mcpcounter_common_groups:
 - "Lymphocytes"
 - "Monocytes"
 - "Neutrophils"
gt_mcp_groups:
 - {new_col: "Lymphocytes", old_cols: ["lymphocyte"]}  
 - {new_col: "Monocytes", old_cols: ["monocyte"]}
 - {new_col: "Neutrophils", old_cols: ["neutrophil"]}
mcp_gt_groups:
  - {new_col: "Monocytes", old_cols: ["Monocytic_lineage"]}
  - {new_col: "Lymphocytes", old_cols: ["Cytotoxic_lymphocytes"]}  
pca_plot_aes:
  
  
