---
title: "GSE81861 deconvolution plots"
output: html_document
---

```{r setup, include = FALSE, warning = F}
library(plyr)
library(doMC)
library(tidyverse)
library(synapser)
library(data.table)
library(magrittr)
library(RColorBrewer)
library(ggfortify)
library(pheatmap)
library(knitr)

home_dir <- "/home/aelamb/repos/Tumor-Deconvolution-Challenge/"
tmp_dir  <- "/home/aelamb/tmp/tumor_deconvolution/GSE81861/"

annotation_id <- "syn11898281"
count_id      <- "syn11898217"
genes_id       <- "syn11918430"

setwd(home_dir)
source("scripts/utils.R")
setwd(tmp_dir)
synLogin()
registerDoMC(cores = detectCores())
```


```{r transform data, include = FALSE, warning = F}
setwd(tmp_dir)
annotation_df <- annotation_id %>% 
    create_df_from_synapse_id("./") %>% 
    select(title, characteristics_ch1) %>% 
    separate(characteristics_ch1, c("string", "person"), ": ") %>% 
    mutate(person = str_replace_all(person, ";", "")) %>% 
    select(title, person) %>% 
    set_names(c("sample", "person"))

count_df <- create_df_from_synapse_id(count_id, "./") 

gene_df <-  create_df_from_synapse_id(genes_id)

mcp_genes <- gene_df %>% 
    filter(Method == "mcpcounter") %>%
    use_series("Hugo")
    
cs_genes <- gene_df %>% 
    filter(Method == "cibersort") %>%
    use_series("Hugo")

sample_metadata_df <- count_df %>% 
    .[1:3] %>% 
    left_join(annotation_df, by = c("cell_id" = "sample")) %>% 
    mutate(cell_type = replace_na(cell_type, "Unknown")) %>% 
    mutate(combined_name = str_c(person, "_", cell_type))
    
cpm_matrix <- count_df %>% 
    select(-c(sample_id, cell_type)) %>% 
    df_to_matrix("cell_id") %>% 
    t %>% 
    apply(2, calculate_cpm)

mean_cpm_matrix <- sample_metadata_df %>%
    split(.$combined_name) %>%
    map(use_series, cell_id) %>%
    map(get_summary_by_matrix_cols, cpm_matrix, mean) %>%
    do.call("cbind", .) %>% 
    .[!rowSums(.) == 0,]

mcp_zscore_matrix <- mean_cpm_matrix %>% 
    .[rownames(.) %in% mcp_genes,] %>% 
    zscore_matrix
    
cs_zscore_matrix <- mean_cpm_matrix %>% 
    .[rownames(.) %in% cs_genes,] %>% 
    zscore_matrix

mcp_heatmap_row_df <- gene_df %>% 
    filter(Method == "mcpcounter") %>% 
    filter(Hugo %in% rownames(mcp_zscore_matrix)) %>% 
    select(-Method) %>% 
    arrange(Hugo) %>% 
    data.frame %>% 
    column_to_rownames("Hugo") %>% 
    set_names("Reference cell type")

mcp_heatmap_col_df <- sample_metadata_df %>%
    select(combined_name, person, cell_type) %>% 
    distinct %>% 
    arrange(combined_name) %>% 
    data.frame %>% 
    column_to_rownames("combined_name") %>% 
    set_names(c("Sample", "Mixture cell type"))


person_metadata_df <- sample_metadata_df %>%
    select(-cell_id) %>%
    distinct %>%
    arrange(person, cell_type) 

cs_result_df <- "cs_results.tsv" %>% 
    read_tsv %>% 
    transpose_df("cell_type", "cell_type")

mcp_result_df <- read_tsv("mcp_results.tsv")


```



```{r PCA plots}
autoplot(prcomp(t(mcp_zscore_matrix)), data = person_metadata_df, colour = 'person', main = "MCPCounter")
autoplot(prcomp(t(mcp_zscore_matrix)), data = person_metadata_df, colour = 'cell_type', main = "MCPCounter")
autoplot(prcomp(t(cs_zscore_matrix)), data = person_metadata_df, colour = 'person', main = "Cibersort")
autoplot(prcomp(t(cs_zscore_matrix)), data = person_metadata_df, colour = 'cell_type', main = "Cibersort")
```

```{r, fig.align = "center", fig.height = 20, fig.width = 16}
pheatmap(
    mcp_zscore_matrix, 
    main = "MCPCounter", 
    annotation_row = mcp_heatmap_row_df,
    annotation_col = mcp_heatmap_col_df,
    scale = "none")
```

```{r, fig.align = "center", fig.height = 60, fig.width = 16}
pheatmap(
    cs_zscore_matrix,
    main = "Cibersort", 
    annotation_col = mcp_heatmap_col_df,
    scale = "none")
```

```{r, results}
kable(mcp_result_df)
kable(cs_result_df)
```


