synapse_ids:
  cibersort_results: "syn12978689"
  ground_truth: "syn12666962"
  mcpcounter_results: "syn12978690"
  log_tpm_expression: "syn12979071"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn12667620"
cibersort_common_groups:
 - "B_cells"
 - "CD4_T_cells" 
 - "CD8_T_cells" 
 - "NK_cells"
 - "Other_cells"
mcpcounter_common_groups:
 - "B_cells"
 - "NK_cells"
 - "T_cells"
cs_gt_groups: 
  - {new_col: "B_cells", old_cols: ["B_cells_naive", "B_cells_memory"]}
  - {new_col: "CD4_T_cells", old_cols: ["T_cells_CD4_memory_resting", "T_cells_CD4_memory_activated"]}
  - {new_col: "CD8_T_cells", old_cols: "T_cells_CD8"}
  - {new_col: "NK_cells", old_cols: ["NK_cells_resting",  "NK_cells_activated"]} 
  - {new_col: "Other_cells", old_cols: ["Plasma_cells", "T_cells_follicular_helper", "T_cells_gamma_delta", 
  "Monocytes", "Macrophages_M0", "Macrophages_M1", "Macrophages_M2", "Dendritic_cells_resting", 
  "Dendritic_cells_activated", "Mast_cells_resting", "Mast_cells_activated", "Eosinophils", "Neutrophils"]}
mcp_gt_groups: 
  - {new_col: "B_cells", old_cols: "B_lineage"}
gt_cs_groups:
gt_mcp_groups:
- {new_col: "T_cells", old_cols: ["CD4_T_cells", "CD8_T_cells"]}
pca_plot_aes:
  color: 
  shape: "gender"
  size: "age"
  
  
