---
title: "GSE62408 deconvolution plots"
output: html_document
---

```{r setup, include = FALSE, warning = F}
library(plyr)
library(doMC)
library(tidyverse)
library(synapser)
library(data.table)
library(magrittr)
library(pheatmap)
library(knitr)

home_dir <- "/home/aelamb/repos/Tumor-Deconvolution-Challenge/"
tmp_dir  <- "/home/aelamb/tmp/tumor_deconvolution/GSE62408/"

count_id      <- "syn11915424"
genes_id       <- "syn11918430"

setwd(home_dir)
source("scripts/utils.R")
setwd(tmp_dir)
synLogin()
registerDoMC(cores = detectCores())
```


```{r transform data, include = FALSE, warning = F}
setwd(tmp_dir)

rpkm_df <- create_df_from_synapse_id(count_id, unzip = T) %>% 
    dplyr::rename("Hugo" = `-`)
    
gene_df <-  create_df_from_synapse_id(genes_id)

mcp_genes <- gene_df %>% 
    filter(Method == "mcpcounter") %>%
    use_series("Hugo")
    
cs_genes <- gene_df %>% 
    filter(Method == "cibersort") %>%
    use_series("Hugo")

mcp_zscore_matrix <- rpkm_df %>% 
    filter(Hugo %in% mcp_genes) %>% 
    group_by(Hugo) %>% 
    summarise_all(mean) %>% 
    df_to_matrix("Hugo") %>% 
    zscore_matrix

cs_zscore_matrix <- rpkm_df %>% 
    filter(Hugo %in% cs_genes) %>% 
    group_by(Hugo) %>% 
    summarise_all(mean) %>% 
    df_to_matrix("Hugo") %>% 
    zscore_matrix

mcp_df <- gene_df %>% 
    filter(Method == "mcpcounter") %>% 
    filter(Hugo %in% rownames(mcp_zscore_matrix)) %>% 
    select(-Method) %>% 
    arrange(Hugo) %>% 
    data.frame %>% 
    column_to_rownames("Hugo") %>% 
    set_names("Cell Type")

cs_result_df <- "cs_results.tsv" %>% 
    read_tsv %>% 
    transpose_df("cell_type", "cell_type")

mcp_result_df <- read_tsv("mcp_results.tsv")
   
```

```{r, fig.align = "center", fig.height = 20, fig.width = 8}
pheatmap(mcp_zscore_matrix, main = "MCPCounter", annotation_row = mcp_df, scale = "none")
```

```{r, fig.align = "center", fig.height = 60, fig.width = 8}
pheatmap(cs_zscore_matrix, main = "Cibersort", scale = "none")
```

```{r, results}
kable(mcp_result_df)
kable(cs_result_df)
```



