synapse_ids:
  cibersort_results: "syn17024904"
  mcpcounter_results: "syn17024902"
  ground_truth: "syn15664977"
  log_tpm_expression: "syn15667753"
  cibersort_genes: "syn12184137"
  mcpcounter_genes: "syn11918430"
  annotations: "syn15664976"
cibersort_common_groups:
 - "Activated_memory_CD4_T_cells"
 - "CD8_T_cells"
 - "Gamma_delta_T_cells"
 - "Memory_B_cells"
 - "Monocytes"
 - "Naive_B_cells"
 - "Naive_CD4_T_cells"
 - "NK_cells"
 - "Resting_memory_CD4_T_cells"
gt_cs_groups:
cs_gt_groups: 
  - {new_col: "Activated_memory_CD4_T_cells", old_cols: ["T_cells_CD4_memory_activated"]}
  - {new_col: "CD8_T_cells", old_cols: ["T_cells_CD8"]}
  - {new_col: "Gamma_delta_T_cells", old_cols: ["T_cells_gamma_delta"]}
  - {new_col: "Memory_B_cells", old_cols: ["B_cells_memory"]}
  - {new_col: "Naive_B_cells", old_cols: ["B_cells_naive"]}
  - {new_col: "Naive_CD4_T_cells", old_cols: ["T_cells_CD4_naive"]}
  - {new_col: "NK_cells", old_cols: ["NK_cells_resting", "NK_cells_activated"]}
  - {new_col: "Resting_memory_CD4_T_cells", old_cols: ["T_cells_CD4_memory_resting"]}
mcpcounter_common_groups:
 - "CD8_T_cells"
 - "T_cells"
 - "NK_cells"
 - "B_lineage"
 - "Monocytes"
gt_mcp_groups:
  - {new_col: "T_cells", old_cols: ["Activated_memory_CD4_T_cells", "Resting_memory_CD4_T_cells", "CD8_T_cells"]}
  - {new_col: "B_lineage", old_cols: ["Memory_B_cells", "Naive_B_cells"]}
mcp_gt_groups:
  - {new_col: "Monocytes", old_cols: ["Monocytic_lineage"]}
pca_plot_aes:
  
  
